POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Watty Mu",
    "number": 11111111
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "wat"
}